services:
  app:
    build: .
    expose:
      - "8082:8082"


  express:
    image: mongo-express
    container_name: mongo-express-ui
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=user
      - ME_CONFIG_MONGODB_ADMINPASSWORD=pass
      - ME_CONFIG_MONGODB_SERVER=db
    ports:
      - "8083:8083"
    depends_on:
      - db

  db:
    image: mongo:latest
    container_name: mongodb-database
    volumes:
      - mongodata:/data/db
      - config:/data/configdb
    ports:
      - "27016:27016"
    environment:
      - MONGODB_INITDB_ROOT_USERNAME=user
      - MONGODB_INITDB_ROOT_PASSWORD=pass

volumes:
  mongodata:
  config: