services:
  app:
    build: .
    container_name: gt-application
    volumes:
      - .:/app
    ports:
      - "8082:8082"
    networks:
      - application
    depends_on:
      - db


  express:
    image: mongo-express
    container_name: mongo-express-ui
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=user
      - ME_CONFIG_MONGODB_ADMINPASSWORD=pass
      - ME_CONFIG_MONGODB_SERVER=db
    ports:
      - "8083:8081"
    expose:
      - "8083"
    networks:
      - application
    depends_on:
      - db

  db:
    build: ./.docker/database
    container_name: mongodb-database
    volumes:
      - ./.docker/volume/mongodb:/data/db
    ports:
      - "27016:27016"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=docker
    networks:
      - application


networks:
  application:
    driver: bridge