services:
  app:
    build: .
    container_name: gt-application
    volumes:
      - .:/app
    ports:
      - "8082:8082"
    networks:
      - application
    depends_on:
      db:
        condition: service_healthy
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://root:docker@db:27017/toysdb?authSource=admin

  db:
    image: mongo:4.4
    container_name: mongodb
    hostname: mongo
    restart: unless-stopped
    volumes:
      - mongon_data_container:/data/db
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=docker
      - MONGO_INITDB_DATABASE=toysdb
      - MONGO_DB_USERNAME=admin
      - MONGO_DB_PASSWORD=admin
    networks:
      - application
    command: ["--bind_ip", "0.0.0.0"]
    healthcheck:
      test: [ "CMD", "mongo", "--eval", "db.adminCommand('ping')" ]
      interval: 10s
      timeout: 10s
      retries: 5



networks:
  application:
    driver: bridge

volumes:
  mongon_data_container: