spring:
  application:
    name: Gt-Solar-backend

  profiles:
    active: development
  servlet:
    multipart:
      enabled: true
      max-file-size: 200MB
      max-request-size: 200MB
server:
  port: 8082

springdoc:
  swagger-ui:
    path: /swagger