spring:
  application:
    name: Gt-Solar-backend
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${EMAILUSERNAME}
    password: ${EMAILPASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  profiles:
    active: development
  servlet:
    multipart:
      enabled: true
      max-file-size: 200MB
      max-request-size: 200MB
server:
  port: 8082

springdoc:
  swagger-ui:
    path: /swagger